server:
  port: 10005

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: weather

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.weather: DEBUG